import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css"
import { Navbar } from "./(commonLayout)/components/Navbar";
import { Footer } from "./(commonLayout)/components/Footer";
import { Toaster } from "sonner";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MediStore  ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        {children}


      </body>
    </html>
  );
}
